Repository needsguidance/Semref, pull requests merged in 2019-10, with the labels that each got.

#2 Generate obj
  __pycache__/assembler.cpython-36.pyc
  assembler.py
  input/test.asm
  input/test1.asm
  input/test2.asm
  main.py
  read.py
Labels: good first issue

#3 Added error detection.
  assembler.py
  main.py
Labels: enhancement, good first issue

#4 Add Program Counter (PC) improvements and bug fixes on store instruct…
  assembler.py
Labels: enhancement, good first issue

#5 Updated assembler.py to handle org errors appropriately.
  assembler.py
  main.py
Labels: enhancement

#6 To binary converter
  __pycache__/assembler.cpython-36.pyc
  assembler.py
  main.py
Labels: enhancement

#7 Converts into binary variables, constants and labels
  .gitignore
  __pycache__/assembler.cpython-36.pyc
  assembler.py
  main.py
Labels: enhancement

#10 Ng 19 1024x650 window
  GUI/test.kv
  GUI/window.py
  main.py
  output/out.obj
  requirements.txt
Labels: enhancement

#13 Ng 13 step by step instructions
  GUI/table.py
  GUI/window.py
  __pycache__/assembler.cpython-36.pyc
  main.py
  microprocessor_simulator.py
Labels: enhancement

#14 Fixed naming error
  GUI/window.py
  microprocessor_simulator.py
  output/debugger.txt
Labels: enhancement

#15 Ng 11 view register values
  GUI/window.py
  constants.py
  microprocessor_simulator.py
  requirements.txt
Labels: enhancement

#16 Ng 12 show memory
  GUI/table.py
  GUI/window.py
  microprocessor_simulator.py
  output/debugger.txt
Labels: enhancement

#18 Ng 10 disassembled instructions
  GUI/window.py
  main.py
  microprocessor_simulator.py
  output/debugger.txt
  output/out1.obj
Labels: enhancement

#21 Ng 16 save file
  GUI/window.py
  microprocessor_simulator.py
Labels: enhancement

#22 bug fix
  microprocessor_simulator.py
  output/debugger.txt
Labels: enhancement

#23 Ng 24 traffic lights
  GUI/window.py
  __pycache__/assembler.cpython-36.pyc
  assembler.py
  main.py
  microprocessor_simulator.py
Labels: enhancement

#24 Ng 27 hex keyboard
  GUI/.gitignore
  GUI/window.py
  constants.py
  microprocessor_simulator.py
Labels: enhancement, good first issue

#26 Ng 25 segment display
  GUI/window.py
  main.py
  microprocessor_simulator.py
Labels: enhancement

#25 Ng 26 ascii display
  GUI/window.py
Labels: enhancement

#27 Ng 16 save file
  GUI/window.py
  output/debugger.txt
Labels: enhancement

#29 Ng 23 configure I/O ports
  GUI/semref.ini
  GUI/window.py
  constants.py
  microprocessor_simulator.py
Labels: enhancement

#30 Fixed inconsistent window behaviour
  GUI/window.py
Labels: good first issue
