Repository needsguidance/Semref, pull requests merged in 2019-11, with the labels that each got.

#31 Used a different approach to set window properties
  GUI/semref.ini
  GUI/window.py
  install.py
Labels: bug

#32 Ng 34 restrict ports
  GUI/window.py
  constants.py
Labels: enhancement

#33 Ng 33 assembler tests
  input/test.asm
  input/test10.asm
  input/test11.asm
  input/test3.asm
  input/test4.asm
  input/test5.asm
  input/test6.asm
  input/test7.asm
  input/test8.asm
  input/test9.asm
  tests/test_assembler.py
  tests/test_valid_input.py
Labels: enhancement, test

#36 Ng 36 fix traffic lights
  GUI/window.py
  microprocessor_simulator.py
Labels: Fixes

#38 Ng 40 update i/o on port change
  GUI/window.py
  install.py
  main.py
Labels: Fixes

#37 Add conditional bit to registers for display this value on REGISTER T…
  constants.py
  microprocessor_simulator.py
Labels: enhancement

#39 Integrated assembler to load file functionality in GUI.
  GUI/window.py
  constants.py
  main.py
  microprocessor_simulator.py
  output/out1.obj
Labels: enhancement

#40 Code cleanup and optimization
  GUI/.gitignore
  GUI/semref.kv
  GUI/window.py
  output/test.obj
Labels: Fixes, good first issue

#41 Ng 41 add assembler to gui
  GUI/window.py
Labels: bug

#43 Ng 52 bug fix file loader
  GUI/window.py
Labels: bug

#45 Seven Segment Bug Fix
  GUI/window.py
Labels: bug

#46 Ng 48 cross platform windows
  GUI/semref.kv
  GUI/window.py
  constants.py
  images/plain-white-background.jpg
  requirements.txt
Labels: bug

#47 Immediate instructions display "#" on disassembly
  GUI/window.py
Labels: bug

#48 Fixed Instructions Table for dpi screens < 192
  GUI/window.py
Labels: Fixes

#49 Ng 55 io dialog window fix
  GUI/window.py
Labels: Fixes, good first issue

#44 Ng 42 visual indicators depend of Ng 48
  GUI/window.py
  assembler.py
  microprocessor_simulator.py
  utils.py
Labels: enhancement

#50 Fixed ascii grid positioning for high display screens
  GUI/window.py
Labels: Fixes, bug

#51 Added ReadMe file.
  README.md
Labels: documentation

#52 Ng 43 code editor
  GUI/semref.kv
  GUI/window.py
  microprocessor_simulator.py
  utils.py
Labels: bug, enhancement

#53 Added Inconsolata-regular font to text editor
  GUI/window.py
  assets/fonts/Inconsolata-Regular.ttf
  assets/images/logo.jpg
  assets/images/plain-white-background.jpg
  output/test8.obj
Labels: enhancement

#56 Create LICENSE
  LICENSE
Labels: documentation

#57 Utilizing nose testing framework for better coverage integration.
  .coveragerc
  README.md
  install.py
Labels: test

#59 Ng 49 cleanup optimization
  GUI/IO/devices.py
  GUI/semref.kv
  GUI/window.py
  lexer.py
  main.py
  microprocessor_simulator.py
  utils.py
Labels: enhancement

#61 Added tests for indentation.
  assembler.py
  input/indent_test1.asm
  input/indent_test2.asm
  input/indent_test3.asm
  input/indent_test4.asm
  input/indent_test5.asm
  input/indent_test6.asm
  tests/test_assembler.py
Labels: test

#62 Created check for mixed cases of instructions on run.
  assembler.py
Labels: bug

#64 Fixed bug on the updating of reserved ports
  GUI/window.py
Labels: bug

#66 Fixed read me
  README.md
Labels: documentation
